#+TITLE: GOOD LUCK WITH THAT PUBLIC LICENSE
#+DATE: Version 1, June 19 2018
#+AUTHOR: LICNSE by me-shaon. Typed by thecsw.
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: 
#+DESCRIPTION: Good Luck With That Public License
#+KEYWORDS: Public Software License
#+LATEX_COMPILER: pdflatex
#+OPTIONS: toc:nil author:nil

Copyright \copyright\text{ }  Everyone, except Author.

#+BEGIN_CENTER
Everyone is permitted to copy, distribute, modify, merge, sell, publish,
sublicense or whatever they want with this software but at their OWN RISK.
#+END_CENTER

\bigskip

\renewcommand{\abstractname}{Preamble}
\begin{abstract}
 The author has absolutely no clue what the code in this project does.
It might just work or not, there is no third option.
\end{abstract}

\bigskip

#+BEGIN_CENTER
GOOD LUCK WITH THAT PUBLIC LICENSE

TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION, AND MODIFICATION
#+END_CENTER

0. You just DO WHATEVER YOU WANT TO as long as you NEVER LEAVE A TRACE TO TRACK
   THE AUTHOR of the original product to blame for or hold responsible. \newline
   \newline IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
   OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
   IN THE SOFTWARE.

\bigskip
#+BEGIN_QUOTE
Good luck and Godspeed.
#+END_QUOTE
